// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package mp2.ng.hw.hw4.Battleship;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import mp2.ng.hw.hw4.Battleship.Field;
import mp2.ng.hw.hw4.Battleship.Player;
import mp2.ng.hw.hw4.Battleship.Player.Point;

/************************************************************/
/**
 * 
 */
//class A{
//	void m(){
//		System.out.println(a);
//	}
//}
public class Game {
	/**
	 * 
	 */
	private Player player1;
	private Player player2;
	
	private Player offendingPlayer; 
	public void initGame(){
		// PC vs PC
		offendingPlayer = player1 = new PlayerGUI("GUI1");	
		player2 = new PC("pc2");
		
		player1.enemy = player2;
		player2.enemy = player1;
	}
	void nextPlayer(){
		if(offendingPlayer == player1){
			offendingPlayer = player2;
		}else{
			offendingPlayer = player1;	
		}
	}
	private static class Test{
		private void name() {
			System.out.println("Test");
		}
	}
	private static class Test2 extends Test{
		public void name() {
			System.out.println("Test2");
		}
	}
	public void startGame(){
		new Test().name();
		Test t1 = new Test2();
		t1.name();
		//choose who's first
		Random random = new Random();
		if(random.nextBoolean())
			nextPlayer();
		
		int turn = 0;
		Field.AtackResult atackResult;
		do{
			System.out.println(offendingPlayer.name  + " turn " + ++turn);
			try {
				Thread.sleep(300);
			} catch (InterruptedException e) {}
			
			atackResult = offendingPlayer.makeTurn();

			if(atackResult == Field.AtackResult.MISS)
				nextPlayer();
//			else
//				System.out.println(offendingPlayer.enemy.renderForEnemy());

		}while(atackResult != Field.AtackResult.WIN);

		System.out.println("Player " + offendingPlayer + " wins" );
	}
	public static void main(String[] args){
		Game game = new Game();
		game.initGame();
		game.startGame();
	}
}
