// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package mp2.ng.hw.hw4.Battleship;

import mp2.ng.hw.hw4.Battleship.Player;

/************************************************************/
/**
 * 
 */
public class UI {
};
