// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package mp2.ng.hw.Battleship;

/************************************************************/
/**
 * 
 */
public class Cell {
	int x;
	int y;
	
	private boolean aShip;
	private boolean wasShip;
	private boolean surround;
	private boolean wasBombed;
	Ship ship;
	
	Cell(int y, int x) {
		this.x = x;
		this.y = y;
	}
	
	public boolean isAShip() {
		return aShip;
	}
	public void setWasShip() {
		wasShip = true;
	}
	public boolean isWasShip() {
		return wasShip;
	}
	public boolean isSurround() {
		return surround;
	}
	public void setSurround(boolean surround) {
		this.surround = surround;
	}
	public void setShip(Ship ship) {
		this.ship = ship;
		aShip = true;
	}
	public void removeShip() {
		this.ship = null;
		aShip = false;
	}
	public void beenBombed(){
		wasBombed = true;
	}
	
	public boolean isWasBombed() {
		return wasBombed;
	}

	@Override
	public String toString(){
		if(isAShip()) return String.valueOf(ship.getSize());
		if(isWasShip()) return new String("x");
		if(isWasBombed()) return new String(".");
		if(isSurround()) return new String("_");
		return new String(" ");
	}
}
