// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package mp2.ng.hw.Battleship;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import mp2.ng.hw.Battleship.Field;
import mp2.ng.hw.Battleship.Player;
import mp2.ng.hw.Battleship.Player.Point;

/************************************************************/
/**
 * 
 */
//class A{
//	void m(){
//		System.out.println(a);
//	}
//}
public class Game {
	/**
	 * 
	 */
	private Player player1;
	private Player player2;
	
	private Player offendingPlayer; 
	private Player defendingPlayer;

	
	
	public void initGame(){
		// PC vs PC
		offendingPlayer = player1 = new PC("pc1");	
		defendingPlayer = player2 = new PC("pc2");
	}
	void nextPlayer(){
		if(offendingPlayer == player1){
			offendingPlayer = player2;
			defendingPlayer = player1;
		}else{
			offendingPlayer = player1;
			defendingPlayer = player2;	
		}
	}
	
	public void startGame(){
		//choose who's first
		Random random = new Random();
		if(random.nextBoolean())
			nextPlayer();
		
		Point point;
		Field.AtackResult atackResult;
		do{
			try {
				Thread.sleep(300);
			} catch (InterruptedException e) {}

			point = offendingPlayer.makeShot();
			atackResult= defendingPlayer.surviveBombardment(point);
			System.out.println(offendingPlayer.name  +" " + point.x +" " + point.y);
			
			
			offendingPlayer.setResult(atackResult);
			offendingPlayer.updateEnemyView(defendingPlayer.renderForEnemy());
			if(atackResult == Field.AtackResult.MISS)
				nextPlayer();
			else
				System.out.println(defendingPlayer.renderForEnemy());

		}while(atackResult != Field.AtackResult.WIN);

		System.out.println("Player " + offendingPlayer + "wins" );
	}
	public static void main(String[] args){
		Game game = new Game();
		game.initGame();
		game.startGame();
	}
}
