// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package mp2.ng.hw.Battleship;

import java.util.Random;

/************************************************************/
/**
 * 
 */
public class PC extends Player{
	int[][] tracking = new int[10][10];
	PC(){

	}
	PC(String name){
		this.name = name;
	}
	@Override
	public Point makeShot() {
		Random random = new Random();
		Point point = new Point();
		point.y = random.nextInt(10);
		point.x = random.nextInt(10);
		tracking[point.x][point.y] = 1;
		return point;	
	}

	@Override
	public void updateOwnView(String field) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void updateEnemyView(String field) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Point setResult(String s) {
		// TODO Auto-generated method stub
		switch(s){
		case "HIT":
		}
		return null;
	}
}
