// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package mp2.ng.hw.Battleship;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	String name;
	int [][] trackingField;
	public static class Point{
		int x;
		int y;
	}
	public abstract Point makeShot();
	public abstract Point setResult(String s);
	public abstract void updateOwnView(String field);
	public abstract void updateEnemyView(String field);
	public String toString(){
		return name;	
	}
}
